### ISSUE TITLE
bs4 error 

### ISSUE THREAD

**Issue by Floppaboppa** [LameLemon/archive-chan#8]
i get this error when trying to download a thread

Traceback (most recent call last):
  File "C:\Users\user\Downloads\archive-chan\archiver.py", line 8, in <module>
    from extractors.extractor import Extractor
  File "C:\Users\user\Downloads\archive-chan\extractors\extractor.py", line 1, in <module>
    from bs4 import BeautifulSoup as soup
ModuleNotFoundError: No module named 'bs4'

ive already done "pip install beautifulsoup4" and "pip3 install -r requirements.txt" but it still throws the same error
any help please?

**Comment by PeskyPotato** [comment]
Hey @Floppaboppa, thanks for checking out the project. I will be honest I haven't used it in a while so can't confirm if the code is still valid. However to fix the bs4 module installation can you try the following:
```
python3 -m pip install -U bs4
```

Replace `python3` which whatever executible you use to run the program. i.e. `python` or `python3`.
